platform :ios, '9.0'

target 'Senti' do
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'Firebase/Core', '6.3.0'
  pod 'Firebase/Auth', '6.3.0'
  pod 'Firebase/Storage', '6.3.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'
  pod 'GoogleSignIn', '4.4.0'
  pod 'FBSDKCoreKit', '4.40.0'
  pod 'FBSDKLoginKit', '4.40.0'
  pod 'FBSDKShareKit', '4.40.0'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end
